### ISSUE TITLE
Renaming .paml file does not rename code-behind file.

### ISSUE THREAD

**Issue by grokys** [Perspex/PerspexVS#13]
Migrated from https://github.com/Perspex/Perspex/issues/381

**Comment by abdelkarim** [comment]
This issue does not occur with xaml files, and we've already switched the perspex templates and the designer to xaml.

I guess no need to try and fix this.

![issue-fixed](https://cloud.githubusercontent.com/assets/1153480/13078365/bdefbc52-d4be-11e5-9b8b-9980acf19aa5.gif)

**Comment by grokys** [comment]
Great news! I will close the issue then.
