### ISSUE TITLE
Handling Updates to DesignerApi

### ISSUE THREAD

**Issue by Seeker1437** [Perspex/PerspexVS#30]
I have created a PR ( #29 ) that adds Perspex as a submodule and then links the `DesignerApi.cs` file to the designer so that it will pull the most up to date file from the repo and build.

I have opened this issue because even though this is nice, the designer only needs a single file from the Perspex repo. Additionally, this file is not updated often enough to warrant this to be really needed.

Should we bring the this PR into the repo (where `DesignerApi.cs` is pulled from the submodule) or should we stick to keep the file locally and keeping that up to date manually?

**Comment by grokys** [comment]
Yeah, personally I'm not sure one file warrants a git submodule and the hassle it creates for newcomers trying to get started.

**Comment by Seeker1437** [comment]
Based off the general majority in both private and public forms, we will stick to manually updating `DesignerApi.cs` as needed.
